### ISSUE TITLE
Maybe ServerNameList is too much

### ISSUE THREAD

**Issue by martinthomson** [grittygrease/tls13-post-handshake-auth#6]
Given that type 0 is the only type of server name that can ever be supported (see agl's email on the topic), we might be able to just commit to including a domain name in the request.

**Comment by martinthomson** [comment]
Also, this is more recently defined in [RFC 6066](https://tools.ietf.org/html/rfc6066#section-3).

**Comment by grittygrease** [comment]
Addressed, thanks.
